### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by goodeats** [goodeats/nestjs-appointment-scheduler#1]
Here is the current scope for this project:

- [ ] connect database
- [ ] create doctors entity
- [ ] auth signup for doctors
- [ ] auth signin for doctors
- [ ] allow doctors to update their info
- [ ] create insurance entity
- [ ] doctors many:many insurance
- [ ] create patient entity
- [ ] auth signup patients
- [ ] allow patients to update their info
- [ ] patients one:many insurance
- [ ] create appointment entity
- [ ] patients create appointments, both can read, update, delete

That's plenty for now, other things to consider for another time:

- availability
- appointment date & time (just connect first)
- appointment duration (affects availability)
- specialty / reason for appointment
- insurance confirmed
- out of office

**Comment by goodeats** [comment]
Wrapping up for now, left some comments on the readme
